development:
  adapter: mysql
  encoding: utf-8
  database: mytest
  pool: 5
  username: root
  password:  

test: &test
  adapter: mysql
  encoding: utf-8
  database: mytest
  pool: 5
  username: root
  password:    
